=== ISAITB/validator-resources-json-sample/resources/schemas/PurchaseOrder.schema.json
{
  "$id": "http://itb.ec.europa.eu/sample/PurchaseOrder.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A JSON representation of EU Purchase Orders",
  "type": "object",
  "required": [ "shipTo", "billTo", "orderDate", "items" ],
  "properties": {
    "orderDate": { "type": "string" },
    "shipTo":    { "$ref": "#/definitions/address" },
    "billTo":    { "$ref": "#/definitions/address" },
    "comment":   { "type": "string" },
    "items":     {
      "type": "array",
      "items": { "$ref": "#/definitions/item" },
      "minItems": 1,
      "additionalItems": false
    }
  },
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "name":   { "type": "string" },
        "street": { "type": "string" },
        "city":   { "type": "string" },
        "zip":    { "type": "number" }
      },
      "required": ["name", "street", "city", "zip"]
    },
    "item": {
      "type": "object",
      "properties": {
        "partNum":	   { "type": "string" },
        "productName": { "type": "string" },
        "quantity":    { "type": "number", "minimum": 0 },
        "priceEUR":    { "type": "number", "minimum": 0 },
        "comment":     { "type": "string" }
      },
      "required": ["partNum", "productName", "quantity", "priceEUR"]
    }
  }
}

=== ISAITB/validator-resources-json-sample/etc/sample.json
{
    "shipTo": {
      "name": "John Doe",
      "street": "Europa Avenue 123",
      "city": "Brussels",
      "zip": 1000
    },
    "billTo": {
      "name": "Jane Doe",
      "street": "Europa Avenue 210",
      "city": "Brussels",
      "zip": 1000
    },
    "orderDate": "2020-01-22",
    "comment": "Send in one package please",
    "items": [
      {
        "partNum": "XYZ-123876",
        "productName": "Mouse",
        "quantity": 20,
        "priceEUR": 15.99,
        "comment": "Confirm this is wireless"
      },
      {
        "partNum": "ABC-32478",
        "productName": "Keyboard",
        "quantity": 15,
        "priceEUR": 25.50
      }
    ]
  }
